A logistic regression forward pass

In [5]:

import torch
import torch.nn.functional as F

y = torch.tensor([1.0, 0.0])
x1 = torch.tensor([1.0, 1.0])
w1 = torch.tensor([2.0, 2.0])
b = torch.tensor([0.0, 0.0])

z = x1 * w1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a, y)
print(loss)


tensor(1.1269)


Computing Gradients via Autograd

In [11]:
import torch 
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0, 0.0])
x1 = torch.tensor([1.0, 1.0])
w1 = torch.tensor([2.0, 2.0], requires_grad=True)
b = torch.tensor([0.0, 0.0], requires_grad=True)

z= x1*w1+b
a=torch.sigmoid(z)
loss=F.binary_cross_entropy(a,y)
print(loss)

grad_L_w1= grad(loss, w1, retain_graph=True)
grad_L_b= grad(loss, b, retain_graph=True)
print(grad_L_w1)
print(grad_L_b)


tensor(1.1269, grad_fn=<BinaryCrossEntropyBackward0>)
(tensor([-0.0596,  0.4404]),)
(tensor([-0.0596,  0.4404]),)


A Multilayer perceptron with two hidden layers 

In [4]:
import torch

class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


Number of parameters

In [4]:
num_params = sum(p.numel()for p in model.parameters()if p.requires_grad)
print("total number of trainable moodel parameters", num_params)

total number of trainable moodel parameters 2213


In [5]:
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.1017, -0.1221,  0.0007,  ...,  0.1296,  0.1110, -0.0228],
        [-0.0693, -0.1020,  0.0619,  ..., -0.1146,  0.0495, -0.0371],
        [ 0.0440,  0.0635, -0.0113,  ...,  0.0043, -0.1194, -0.1346],
        ...,
        [ 0.0657,  0.1016,  0.1359,  ...,  0.0342, -0.0192, -0.0429],
        [-0.0574, -0.0767,  0.0516,  ..., -0.0250,  0.0009,  0.0687],
        [ 0.1052, -0.0358, -0.0448,  ...,  0.0558, -0.0249,  0.0282]],
       requires_grad=True)


In [6]:
print(model.layers[0].bias)

Parameter containing:
tensor([ 0.0639, -0.1056,  0.1342,  0.0454, -0.0847,  0.0567,  0.0339, -0.0441,
         0.0772,  0.1258, -0.0892, -0.0857,  0.0425,  0.0019,  0.0564,  0.0249,
        -0.1401,  0.1390,  0.1014, -0.0760,  0.1318, -0.1009, -0.0911, -0.0791,
        -0.0793,  0.0354,  0.0889,  0.0839,  0.0312,  0.0044],
       requires_grad=True)


In [ ]:
print(model.layers[0].weight.shape)

torch.Size([30, 50])


Addding manual seed 


In [5]:
import torch 

torch.manual_seed(123)
model=NeuralNetwork(50,3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [7]:
import torch 
torch.manual_seed(123)
x= torch.rand(1,50)
out=model(x)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)
